#ifndef ROBOTARM_DYNAMIXEL_CONSTANTS_H

#define BROADCAST_ADDRESS 0xFE

// Instructions
#define INST_PING       0x01
#define INST_READ       0x02
#define INST_WRITE      0x03
#define INST_REG_WRITE  0x04
#define INST_ACTION     0x05
#define INST_SYNC_WRITE 0x83

// EEPROM Area Registers
#define REG_MODEL_NUMBER 0x00
#define REG_MODEL_NUMBER_LEN 2

#define REG_FIRMWARE_VERSION 0x02
#define REG_FIRMWARE_VERSION_LEN 1

#define REG_ID 0x03
#define REG_ID_LEN 1

#define REG_BAUD_RATE 0x04
#define REG_BAUD_RATE_LEN 1

#define REG_RETURN_DELAY_TIME 0x05
#define REG_RETURN_DELAY_TIME_LEN 1

#define REG_CW_ANGLE_LIMIT 0x06
#define REG_CW_ANGLE_LIMIT_LEN 2

#define REG_CCW_ANGLE_LIMIT 0x08
#define REG_CCW_ANGLE_LIMIT_LEN 2

#define REG_TEMPERATURE_LIMIT 0x0B
#define REG_TEMPERATURE_LIMIT_LEN 1

#define REG_MIN_VOLTAGE_LIMIT 0x0C
#define REG_MIN_VOLTAGE_LIMIT_LEN 1

#define REG_MAX_VOLTAGE_LIMIT 0x0D
#define REG_MAX_VOLTAGE_LIMIT_LEN 1

#define REG_MAX_TORQUE 0x0E
#define REG_MAX_TORQUE_LEN 2

#define REG_STATUS_RETURN_LEVEL 0x10
#define REG_STATUS_RETURN_LEVEL_LEN 1

#define REG_ALARM_LED 0x11
#define REG_ALARM_LED_LEN 1

#define REG_SHUTDOWN 0x12
#define REG_SHUTDOWN_LEN 1

// RAM Area Registers
#define REG_TORQUE_ENABLE 0x18
#define REG_TORQUE_ENABLE_LEN 1

#define REG_LED 0x19
#define REG_LED_LEN 1

#define REG_CW_COMPLIANCE_MARGIN 0x1A
#define REG_CW_COMPLIANCE_MARGIN_LEN 1

#define REG_CCW_COMPLIANCE_MARGIN 0x1B
#define REG_CCW_COMPLIANCE_MARGIN_LEN 1

#define REG_CW_COMPLIANCE_SLOPE 0x1C
#define REG_CW_COMPLIANCE_SLOPE_LEN 1

#define REG_CCW_COMPLIANCE_SLOPE 0x1D
#define REG_CCW_COMPLIANCE_SLOPE_LEN 1

#define REG_GOAL_POSITION 0x1E
#define REG_GOAL_POSITION_LEN 2

#define REG_MOVING_SPEED 0x20
#define REG_MOVING_SPEED_LEN 2

#define REG_TORQUE_LIMIT 0x22
#define REG_TORQUE_LIMIT_LEN 2

#define REG_PRESENT_POSITION 0x24
#define REG_PRESENT_POSITION_LEN 2

#define REG_PRESENT_SPEED 0x26
#define REG_PRESENT_SPEED_LEN 2

#define REG_PRESENT_LOAD 0x28
#define REG_PRESENT_LOAD_LEN 2

#define REG_PRESENT_VOLTAGE 0x2A
#define REG_PRESENT_VOLTAGE_LEN 1

#define REG_PRESENT_TEMPERATURE 0x2B
#define REG_PRESENT_TEMPERATURE_LEN 1

#define REG_REGISTERED_INSTRUCTION 0x2C
#define REG_REGISTERED_INSTRUCTION_LEN 1

#define REG_MOVING 0x2E
#define REG_MOVING_LEN 1

#define REG_LOCK 0x2F
#define REG_LOCK_LEN 1

#define REG_PUNCH 0x30
#define REG_PUNCH_LEN 2

#endif